package:
  format-version: "1.0.0"
  name: "gfx_apps_sam_d5x_e5x"
  version: "3.10.0"
  type: "application"
  status: "production"

  dependencies:
    - name: "gfx"
      type: "package"
      version: "3.12.0"
    - name: "touch"
      type: "package"
      version: "3.13.0"
