format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_itd}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: RTOSEnabled}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: RTOSMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: VertTouchDataFlip}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: TouchData}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: lib_qtouch}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: lib_qtouch}
- type: ElementPosition
  attributes: {x: '850', y: '100', id: gfx_itd}
