configName: ili9488_rgb565_e51_igat
folderName: legato_qs_e51_igat
format_version: v1.0
frameworkPath: ..\..\..\..\..
processor: ATSAME51J20A
projectName: legato_quickstart_e51_igat
settings:
  PackageFilter: audio;bsp;core;core_apps_pic32mz_da;core_apps_pic32mz_ef;cryptoauthlib;csp;csp_apps_pic32mz_da;csp_apps_pic32mz_ef;csp_apps_sam_c20_c21;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;gfx;gfx_apps;gfx_apps_pic32mz_da;gfx_apps_pic32mz_ef;gfx_apps_sam_9x60;gfx_apps_sam_a5d2;gfx_apps_sam_c20_c21;gfx_apps_sam_d5x_e5x;gfx_apps_sam_e70_s70_v70_v71;gfx_old;quick_docs;touch;usb;wireless
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME51_DFP\3.4.98\atdf\ATSAME51J20A.atdf
