format_version: v1.0
type: UniqueComponent
attributes: {id: sercom0}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: I2CM_BAUD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: '255'}
  - type: Integer
    attributes: {id: I2CS_SDASETUP_TIME_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: '1'}
  - type: Boolean
    attributes: {id: I2CS_SDASETUP_TIME_SUPPORT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: 'true'}
  - type: String
    attributes: {id: RECEIVE_DATA_REGISTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: '&(SERCOM0_REGS->SPIM.SERCOM_DATA)'}
  - type: KeyValueSet
    attributes: {id: SERCOM_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: '1'}
  - type: File
    attributes: {id: SERCOM_SPIM_COMMON_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SERCOM_SPIM_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SERCOM_SPIM_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: SPI_BAUD_RATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_mxt_cpro, value: '8000000'}
  - type: Integer
    attributes: {id: SPI_BAUD_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: '2'}
  - type: KeyValueSet
    attributes: {id: SPI_DIPO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_mxt_cpro, value: '3'}
  - type: Boolean
    attributes: {id: SPI_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: 'true'}
  - type: String
    attributes: {id: TRANSMIT_DATA_REGISTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: '&(SERCOM0_REGS->SPIM.SERCOM_DATA)'}
  - type: Integer
    attributes: {id: USART_BAUD_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: '63522'}
  - type: KeyValueSet
    attributes: {id: USART_FORM}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: '0'}
  - type: Boolean
    attributes: {id: USART_LIN_MASTER_SUPPORTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: 'true'}
  - type: Integer
    attributes: {id: USART_SAMPLE_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: '16'}
  - type: Integer
    attributes: {id: USART_SAMPLE_RATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sercom0, value: '0'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: SERCOM0_I2C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: SERCOM0_SPI}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_spi_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_spi_SPI_dependency}
- type: ElementPosition
  attributes: {x: '40', y: '316', id: sercom0}
