format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_legato}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: LeGPUConnected}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_legato, value: 'true'}
  - type: String
    attributes: {id: driverInitName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_legato, value: ExternalController}
  - type: Menu
    attributes: {id: rtosMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: rtosTaskDelay}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: rtosTaskSize}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '512'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: gfx_driver}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_driver_external}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver_external}
  - type: DirectDependency
    attributes: {id: gpu_driver}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: le_gfx_virtual_gpu}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver_vgpu}
- type: ElementPosition
  attributes: {x: '730', y: '285', id: gfx_legato}
