configName: ili9488_rgb565_e51_igat_rtos
folderName: legato_sc_e51_igat_rtos
format_version: v1.0
frameworkPath: ..\..\..\..\..\..\..\Harmony3Public
processor: ATSAME51J20A
projectName: legato_showcase_e51_igat_rtos
settings:
  PackageFilter: audio;bsp;core;cryptoauthlib;csp;gfx;gfx-ed;quick_docs;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME51_DFP\3.5.104\atdf\ATSAME51J20A.atdf
